import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import {
	Aboutus,
	Footer,
	Gallery,
	Header,
	Hero,
	Introduction,
	Me,
	Projects,
} from '../components';

const Home: NextPage = () => {
	return (
		<div className='scroll-smooth'>
			<Head>
				<title>Raedfish Solutions</title>
				<meta
					name='Raedfish Solution Portfolio'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/raedfish-logo.svg' />
			</Head>

			<div className='scroll-smooth'>
				<Header />
				<Hero />
				<Aboutus />
				<Projects />
				<Me />
				<Introduction />
				<Gallery />
				<Footer />
			</div>
		</div>
	);
};

export default Home;
